### Lekérdezi az alkalmazottakat
GET http://localhost:8080/api/employees

### Lekérdez egy alkalmazottat
GET http://localhost:8080/api/employees/2

### Alkalmazott létrehozása
POST http://localhost:8080/api/employees
Content-Type: application/json

{
    "name": "Jack Doe",
    "yearOfBirth": 1990
}

### Validációs szabály megsértése
POST http://localhost:8080/api/employees
Content-Type: application/json

{
    "name": "J",
    "yearOfBirth": 1322
}

### Alkalmazott módosítása
PUT http://localhost:8080/api/employees/2
Content-Type: application/json

{
   "yearOfBirth": 1991 
}

### Alkalmazott törlése
DELETE http://localhost:8080/api/employees/1